config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # controller#action
  root to: "static_pages#index"

  # definindo rotas para os links no footer das páginas 
  # req get, nome rota, acessa o controller # action
  get 'about', to: 'static_pages#about'
  get 'info_contact', to: 'static_pages#contact'

  # log in
  get 'log_in', to: 'sessions#new'
  post 'log_in', to: 'sessions#create'
  # log_out 
  delete 'sair', to: 'sessions#destroy'

  # rotas padrão de uma arquitetura rest (crud de contatos)
  resources :contacts
  # rotas padrão de uma arquitetura rest (crud de users)
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  # cria e armazena um hash da senha, também gera dois atributos virtuas, o password e o password confimation
  has_secure_password
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum:50 }
  validates :password, length: { minimum:6 }
  validates :email, presence:true, length: { maximum:255 },
                                   format:{ with: VALID_EMAIL_REGEX },
                                   uniqueness: { case_sensitive: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # ação que será executada sempre antes das seguinte actions
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sing_in(user)
      redirect_to user_path(user)
   else
    flash.now[:danger] = 'Invalid email or password'
    render 'new'
   end
  end

  def destroy
    sing_out
    flash[:success] = 'logout successfully'
    redirect_to log_in_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  # definindo a action view
  def index 
    # variavel de instancia 
    @nome = "Vitória"
  end

  # paginas estaticas, actions definidas para links sobre e contatos no footer das paginas
  def about
  end

  def contact
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    # variavel de instancia
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'User registered successfully'
      redirect_to root_url
    else
      render 'new'
    end

  end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sing_in(user)
    session[:user_id] = user.id
  end

  def sing_out
    session.delete[:user_id]
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_singed_in?
    !current_user.nil?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<%# edição e atualização de um contato %>
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <h1>My contacts</h1>
  </div>

  <div class="col-md-8 col-md-offset-2 col-xs-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th colspan="2">
            Actions
            <%= link_to 'New contact', new_contact_path(current_page?), class: 'btn btn-success' %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% if @contacts.empty? %>
          <tr>
            <td colspan="4" class="text-center">
              <h3>No registered contacts.</h3>
              <%= link_to 'click here', new_contact_path(current_page?) %> to register a new contact
            </td>
          </tr>
        <% end %>
        <% @contacts.each do |c| %>
        <tr>
          <td>
            <%= c.name %>
          </td>
          <td>
            <%= c.phone %>
          </td>
          <td>
            <%= link_to 'Show', c %>
          </td>
          <td>
            <%= link_to 'Edit', class: 'btn btn-warning' %>
          </td>
          <td>
            <%= link_to 'Destroy', method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete?' } %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<%# , user_contact_path(current_user, c) %>

app/views/contacts/new.html.erb
<%# cria um novo contato %>
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<%# renderiza um contato já criado (getById) %>
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Ops!Encontramos <%= pluralize(object.errors.count, 'erro', 'errors') %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %> 

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Contact List. All rights reserved.', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%# adicionando o link  o nome da rota criada em routes.rb %>
        <%= link_to 'About', about_path %>
      </li>
      <li>
        <%= link_to 'Contact', contacts_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
    </div>

  <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
  <div class="collapse navbar-collapse" id="expanded-menu">
    <ul class="nav navbar-nav">

    <% if !user_singed_in? %>
        <li class="active">
          <%= link_to 'new account', new_user_path %>
        </li>
    <% end %>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <% if ! user_singed_in? %>
        <li>
          <%= link_to 'Entrar', log_in_path %>
        </li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            welcome, <%= current_user.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'My Page', current_user %>
            </li>
            <li>
              <%= link_to 'Edit', '#' %>
            </li>
            <li class="divider" role="separator"></li>
            <li>
              <%= link_to 'Exit', sair_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">

      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </body>
  
  <%= render 'layouts/footer' %>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>Project created during a <a href="https://www.udemy.com/course/ruby-on-rails-5-na-pratica/">Ruby on Rails course</a> to develop more Rails framework skills</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

<p>Contact <a href="https://www.linkedin.com/in/vit%C3%B3ria-cristina-saturnino-de-moura-6393391b0/">Vitória Moura</a> to find out more about this project</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
   <h1>Contact List</h1>
     <p>Manage your contacts on the go!</p>
     <p> <%= link_to 'Create Your Account', new_user_path, class: 'btn btn-primary btn-lg' %> </p>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-xs-12">
      <h1> Sign Up </h1>
    </div>

    <div class="col-md-6col-md-offset-3col-xs-12">
      <%= form_for @user do |f| %>
      <%# renderizando mensagens ao usuario %>
      <%= render 'layouts/error_messages', object: f.object%>

      <div class="form-group">
        <%= f.label :name  %>
        <%= f.text_field :name, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class:'form-control' %>
      </div>

        <%= f.submit 'Cadastrar', class:'btn btn-primary'  %>
        <% end  %>
    </div>
  </div>

app/views/users/show.html.erb
<h1>oie <%= current_user.name%></h1>